/* indicator-example.c generated by valac 0.16.1, the Vala compiler
 * generated from indicator-example.vala, do not modify */

/*
 * Copyright 2011 Canonical Ltd.
 *
 * This program is free software: you can redistribute it and/or modify it
 * under the terms of the GNU General Public License version 3, as published
 * by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranties of
 * MERCHANTABILITY, SATISFACTORY QUALITY, or FITNESS FOR A PARTICULAR
 * PURPOSE.  See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * Authors:
 *   Marco Trevisan (Treviño) <mail@3v1n0.net>
 */

#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>

#include <gtk/gtk.h>
#include <gobject/gvaluecollector.h>


#define TYPE_INDICATOR_EXAMPLE (indicator_example_get_type ())
#define INDICATOR_EXAMPLE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_INDICATOR_EXAMPLE, IndicatorExample))
#define INDICATOR_EXAMPLE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_INDICATOR_EXAMPLE, IndicatorExampleClass))
#define IS_INDICATOR_EXAMPLE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_INDICATOR_EXAMPLE))
#define IS_INDICATOR_EXAMPLE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_INDICATOR_EXAMPLE))
#define INDICATOR_EXAMPLE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_INDICATOR_EXAMPLE, IndicatorExampleClass))

typedef struct _IndicatorExample IndicatorExample;
typedef struct _IndicatorExampleClass IndicatorExampleClass;
typedef struct _IndicatorExamplePrivate IndicatorExamplePrivate;
typedef struct _Block1Data Block1Data;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
typedef struct _ParamSpecIndicatorExample ParamSpecIndicatorExample;

struct _IndicatorExample {
	GTypeInstance parent_instance;
	volatile int ref_count;
	IndicatorExamplePrivate * priv;
};

struct _IndicatorExampleClass {
	GTypeClass parent_class;
	void (*finalize) (IndicatorExample *self);
};

struct _Block1Data {
	int _ref_count_;
	AppIndicator* indicator;
};

struct _ParamSpecIndicatorExample {
	GParamSpec parent_instance;
};


static gpointer indicator_example_parent_class = NULL;

gpointer indicator_example_ref (gpointer instance);
void indicator_example_unref (gpointer instance);
GParamSpec* param_spec_indicator_example (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void value_set_indicator_example (GValue* value, gpointer v_object);
void value_take_indicator_example (GValue* value, gpointer v_object);
gpointer value_get_indicator_example (const GValue* value);
GType indicator_example_get_type (void) G_GNUC_CONST;
enum  {
	INDICATOR_EXAMPLE_DUMMY_PROPERTY
};
gint indicator_example_main (gchar** args, int args_length1);
static Block1Data* block1_data_ref (Block1Data* _data1_);
static void block1_data_unref (void * _userdata_);
static void _gtk_main_quit_gtk_object_destroy (GtkObject* _sender, gpointer self);
static void __lambda2_ (Block1Data* _data1_);
static void ___lambda2__gtk_menu_item_activate (GtkMenuItem* _sender, gpointer self);
static void __lambda3_ (Block1Data* _data1_);
static void ___lambda3__gtk_menu_item_activate (GtkMenuItem* _sender, gpointer self);
IndicatorExample* indicator_example_new (void);
IndicatorExample* indicator_example_construct (GType object_type);
static void indicator_example_finalize (IndicatorExample* obj);


static Block1Data* block1_data_ref (Block1Data* _data1_) {
	g_atomic_int_inc (&_data1_->_ref_count_);
	return _data1_;
}


static void block1_data_unref (void * _userdata_) {
	Block1Data* _data1_;
	_data1_ = (Block1Data*) _userdata_;
	if (g_atomic_int_dec_and_test (&_data1_->_ref_count_)) {
		_g_object_unref0 (_data1_->indicator);
		g_slice_free (Block1Data, _data1_);
	}
}


static void _gtk_main_quit_gtk_object_destroy (GtkObject* _sender, gpointer self) {
	gtk_main_quit ();
}


static void __lambda2_ (Block1Data* _data1_) {
	AppIndicator* _tmp0_;
	_tmp0_ = _data1_->indicator;
	app_indicator_set_status (_tmp0_, APP_INDICATOR_STATUS_ATTENTION);
}


static void ___lambda2__gtk_menu_item_activate (GtkMenuItem* _sender, gpointer self) {
	__lambda2_ (self);
}


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


static void __lambda3_ (Block1Data* _data1_) {
	AppIndicator* _tmp0_;
	_tmp0_ = _data1_->indicator;
	app_indicator_set_status (_tmp0_, APP_INDICATOR_STATUS_ACTIVE);
}


static void ___lambda3__gtk_menu_item_activate (GtkMenuItem* _sender, gpointer self) {
	__lambda3_ (self);
}


gint indicator_example_main (gchar** args, int args_length1) {
	gint result = 0;
	Block1Data* _data1_;
	GtkWindow* _tmp0_;
	GtkWindow* _tmp1_;
	GtkWindow* win;
	GtkWindow* _tmp2_;
	GtkWindow* _tmp3_;
	GtkWindow* _tmp4_;
	GtkLabel* _tmp5_;
	GtkLabel* _tmp6_;
	GtkLabel* label;
	GtkWindow* _tmp7_;
	GtkLabel* _tmp8_;
	GtkWindow* _tmp9_;
	const gchar* _tmp10_;
	const gchar* _tmp11_;
	AppIndicator* _tmp12_;
	AppIndicator* _tmp13_;
	AppIndicator* _tmp14_;
	AppIndicator* _tmp15_;
	GtkMenu* _tmp16_;
	GtkMenu* _tmp17_;
	GtkMenu* menu;
	GtkMenuItem* _tmp18_;
	GtkMenuItem* _tmp19_;
	GtkMenuItem* item;
	GtkMenuItem* _tmp20_;
	GtkMenuItem* _tmp21_;
	GtkMenu* _tmp22_;
	GtkMenuItem* _tmp23_;
	GtkMenuItem* _tmp24_;
	GtkMenuItem* _tmp25_;
	GtkMenuItem* _tmp26_;
	GtkMenuItem* _tmp27_;
	GtkMenuItem* bar;
	GtkMenuItem* _tmp28_;
	GtkMenuItem* _tmp29_;
	GtkMenu* _tmp30_;
	GtkMenuItem* _tmp31_;
	AppIndicator* _tmp32_;
	GtkMenu* _tmp33_;
	AppIndicator* _tmp34_;
	GtkMenuItem* _tmp35_;
	GtkWindow* _tmp36_;
	_data1_ = g_slice_new0 (Block1Data);
	_data1_->_ref_count_ = 1;
	gtk_init (&args_length1, &args);
	_tmp0_ = (GtkWindow*) gtk_window_new (GTK_WINDOW_TOPLEVEL);
	_tmp1_ = g_object_ref_sink (_tmp0_);
	win = _tmp1_;
	_tmp2_ = win;
	gtk_window_set_title (_tmp2_, "Indicator Test");
	_tmp3_ = win;
	gtk_window_resize (_tmp3_, 200, 200);
	_tmp4_ = win;
	g_signal_connect ((GtkObject*) _tmp4_, "destroy", (GCallback) _gtk_main_quit_gtk_object_destroy, NULL);
	_tmp5_ = (GtkLabel*) gtk_label_new ("Hello, world!");
	_tmp6_ = g_object_ref_sink (_tmp5_);
	label = _tmp6_;
	_tmp7_ = win;
	_tmp8_ = label;
	gtk_container_add ((GtkContainer*) _tmp7_, (GtkWidget*) _tmp8_);
	_tmp9_ = win;
	_tmp10_ = gtk_window_get_title (_tmp9_);
	_tmp11_ = _tmp10_;
	_tmp12_ = app_indicator_new (_tmp11_, "indicator-messages", APP_INDICATOR_CATEGORY_APPLICATION_STATUS);
	_data1_->indicator = _tmp12_;
	_tmp13_ = _data1_->indicator;
	if (!IS_APP_INDICATOR (_tmp13_)) {
		result = -1;
		_g_object_unref0 (label);
		_g_object_unref0 (win);
		block1_data_unref (_data1_);
		_data1_ = NULL;
		return result;
	}
	_tmp14_ = _data1_->indicator;
	app_indicator_set_status (_tmp14_, APP_INDICATOR_STATUS_ACTIVE);
	_tmp15_ = _data1_->indicator;
	app_indicator_set_attention_icon (_tmp15_, "indicator-messages-new");
	_tmp16_ = (GtkMenu*) gtk_menu_new ();
	_tmp17_ = g_object_ref_sink (_tmp16_);
	menu = _tmp17_;
	_tmp18_ = (GtkMenuItem*) gtk_menu_item_new_with_label ("Foo");
	_tmp19_ = g_object_ref_sink (_tmp18_);
	item = _tmp19_;
	_tmp20_ = item;
	g_signal_connect_data (_tmp20_, "activate", (GCallback) ___lambda2__gtk_menu_item_activate, block1_data_ref (_data1_), (GClosureNotify) block1_data_unref, 0);
	_tmp21_ = item;
	gtk_widget_show ((GtkWidget*) _tmp21_);
	_tmp22_ = menu;
	_tmp23_ = item;
	gtk_menu_shell_append ((GtkMenuShell*) _tmp22_, (GtkWidget*) _tmp23_);
	_tmp24_ = (GtkMenuItem*) gtk_menu_item_new_with_label ("Bar");
	_tmp25_ = g_object_ref_sink (_tmp24_);
	_g_object_unref0 (item);
	item = _tmp25_;
	_tmp26_ = item;
	_tmp27_ = _g_object_ref0 (_tmp26_);
	bar = _tmp27_;
	_tmp28_ = item;
	gtk_widget_show ((GtkWidget*) _tmp28_);
	_tmp29_ = item;
	g_signal_connect_data (_tmp29_, "activate", (GCallback) ___lambda3__gtk_menu_item_activate, block1_data_ref (_data1_), (GClosureNotify) block1_data_unref, 0);
	_tmp30_ = menu;
	_tmp31_ = item;
	gtk_menu_shell_append ((GtkMenuShell*) _tmp30_, (GtkWidget*) _tmp31_);
	_tmp32_ = _data1_->indicator;
	_tmp33_ = menu;
	app_indicator_set_menu (_tmp32_, _tmp33_);
	_tmp34_ = _data1_->indicator;
	_tmp35_ = bar;
	app_indicator_set_secondary_activate_target (_tmp34_, (GtkWidget*) _tmp35_);
	_tmp36_ = win;
	gtk_widget_show_all ((GtkWidget*) _tmp36_);
	gtk_main ();
	result = 0;
	_g_object_unref0 (bar);
	_g_object_unref0 (item);
	_g_object_unref0 (menu);
	_g_object_unref0 (label);
	_g_object_unref0 (win);
	block1_data_unref (_data1_);
	_data1_ = NULL;
	return result;
}


int main (int argc, char ** argv) {
	g_type_init ();
	return indicator_example_main (argv, argc);
}


IndicatorExample* indicator_example_construct (GType object_type) {
	IndicatorExample* self = NULL;
	self = (IndicatorExample*) g_type_create_instance (object_type);
	return self;
}


IndicatorExample* indicator_example_new (void) {
	return indicator_example_construct (TYPE_INDICATOR_EXAMPLE);
}


static void value_indicator_example_init (GValue* value) {
	value->data[0].v_pointer = NULL;
}


static void value_indicator_example_free_value (GValue* value) {
	if (value->data[0].v_pointer) {
		indicator_example_unref (value->data[0].v_pointer);
	}
}


static void value_indicator_example_copy_value (const GValue* src_value, GValue* dest_value) {
	if (src_value->data[0].v_pointer) {
		dest_value->data[0].v_pointer = indicator_example_ref (src_value->data[0].v_pointer);
	} else {
		dest_value->data[0].v_pointer = NULL;
	}
}


static gpointer value_indicator_example_peek_pointer (const GValue* value) {
	return value->data[0].v_pointer;
}


static gchar* value_indicator_example_collect_value (GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	if (collect_values[0].v_pointer) {
		IndicatorExample* object;
		object = collect_values[0].v_pointer;
		if (object->parent_instance.g_class == NULL) {
			return g_strconcat ("invalid unclassed object pointer for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		} else if (!g_value_type_compatible (G_TYPE_FROM_INSTANCE (object), G_VALUE_TYPE (value))) {
			return g_strconcat ("invalid object type `", g_type_name (G_TYPE_FROM_INSTANCE (object)), "' for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		}
		value->data[0].v_pointer = indicator_example_ref (object);
	} else {
		value->data[0].v_pointer = NULL;
	}
	return NULL;
}


static gchar* value_indicator_example_lcopy_value (const GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	IndicatorExample** object_p;
	object_p = collect_values[0].v_pointer;
	if (!object_p) {
		return g_strdup_printf ("value location for `%s' passed as NULL", G_VALUE_TYPE_NAME (value));
	}
	if (!value->data[0].v_pointer) {
		*object_p = NULL;
	} else if (collect_flags & G_VALUE_NOCOPY_CONTENTS) {
		*object_p = value->data[0].v_pointer;
	} else {
		*object_p = indicator_example_ref (value->data[0].v_pointer);
	}
	return NULL;
}


GParamSpec* param_spec_indicator_example (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags) {
	ParamSpecIndicatorExample* spec;
	g_return_val_if_fail (g_type_is_a (object_type, TYPE_INDICATOR_EXAMPLE), NULL);
	spec = g_param_spec_internal (G_TYPE_PARAM_OBJECT, name, nick, blurb, flags);
	G_PARAM_SPEC (spec)->value_type = object_type;
	return G_PARAM_SPEC (spec);
}


gpointer value_get_indicator_example (const GValue* value) {
	g_return_val_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_INDICATOR_EXAMPLE), NULL);
	return value->data[0].v_pointer;
}


void value_set_indicator_example (GValue* value, gpointer v_object) {
	IndicatorExample* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_INDICATOR_EXAMPLE));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, TYPE_INDICATOR_EXAMPLE));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
		indicator_example_ref (value->data[0].v_pointer);
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		indicator_example_unref (old);
	}
}


void value_take_indicator_example (GValue* value, gpointer v_object) {
	IndicatorExample* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_INDICATOR_EXAMPLE));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, TYPE_INDICATOR_EXAMPLE));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		indicator_example_unref (old);
	}
}


static void indicator_example_class_init (IndicatorExampleClass * klass) {
	indicator_example_parent_class = g_type_class_peek_parent (klass);
	INDICATOR_EXAMPLE_CLASS (klass)->finalize = indicator_example_finalize;
}


static void indicator_example_instance_init (IndicatorExample * self) {
	self->ref_count = 1;
}


static void indicator_example_finalize (IndicatorExample* obj) {
	IndicatorExample * self;
	self = INDICATOR_EXAMPLE (obj);
}


GType indicator_example_get_type (void) {
	static volatile gsize indicator_example_type_id__volatile = 0;
	if (g_once_init_enter (&indicator_example_type_id__volatile)) {
		static const GTypeValueTable g_define_type_value_table = { value_indicator_example_init, value_indicator_example_free_value, value_indicator_example_copy_value, value_indicator_example_peek_pointer, "p", value_indicator_example_collect_value, "p", value_indicator_example_lcopy_value };
		static const GTypeInfo g_define_type_info = { sizeof (IndicatorExampleClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) indicator_example_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (IndicatorExample), 0, (GInstanceInitFunc) indicator_example_instance_init, &g_define_type_value_table };
		static const GTypeFundamentalInfo g_define_type_fundamental_info = { (G_TYPE_FLAG_CLASSED | G_TYPE_FLAG_INSTANTIATABLE | G_TYPE_FLAG_DERIVABLE | G_TYPE_FLAG_DEEP_DERIVABLE) };
		GType indicator_example_type_id;
		indicator_example_type_id = g_type_register_fundamental (g_type_fundamental_next (), "IndicatorExample", &g_define_type_info, &g_define_type_fundamental_info, 0);
		g_once_init_leave (&indicator_example_type_id__volatile, indicator_example_type_id);
	}
	return indicator_example_type_id__volatile;
}


gpointer indicator_example_ref (gpointer instance) {
	IndicatorExample* self;
	self = instance;
	g_atomic_int_inc (&self->ref_count);
	return instance;
}


void indicator_example_unref (gpointer instance) {
	IndicatorExample* self;
	self = instance;
	if (g_atomic_int_dec_and_test (&self->ref_count)) {
		INDICATOR_EXAMPLE_GET_CLASS (self)->finalize (self);
		g_type_free_instance ((GTypeInstance *) self);
	}
}



